import path from 'node:path';
import { mkdir, readFile, readdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { hmac, safeHex, sha256, randomId } from './crypto.mjs';
import { invariant } from './policy.mjs';
const MAX_FILE=5*1024*1024,MAX_TOTAL=25*1024*1024;
const ALLOWED_ROOTS=['contract.yaml','contract.lock','state.json','ledger.jsonl','issues.json','backlog.json','integrations.json','hooks.jsonl','goals','releases','proposals','evidence'];
function safeRelative(value){const text=value.replaceAll('\\','/');invariant(text&&!text.startsWith('/')&&!text.includes('\0'),'ERR_BACKUP_PATH','Invalid backup path');const n=path.posix.normalize(text);invariant(n!=='.'&&n!=='..'&&!n.startsWith('../'),'ERR_BACKUP_PATH','Backup path escapes root');invariant(!/(^|\/)(auth\.json|credentials|private[-_]?key|\.env)(\/|$)/iu.test(n),'ERR_BACKUP_SECRET','Credential-like paths are not allowed in backups');return n;}
function allowedShipping(relative){return ALLOWED_ROOTS.some(root=>relative===root||relative.startsWith(`${root}/`));}
async function walk(base,current='',out=[]){const dir=path.join(base,current);let entries=[];try{entries=await readdir(dir,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return out;throw e;}for(const entry of entries){const rel=safeRelative(path.posix.join(current,entry.name));if(rel==='tmp'||rel.startsWith('tmp/'))continue;const full=path.join(base,rel);if(entry.isSymbolicLink())continue;if(entry.isDirectory())await walk(base,rel,out);else if(entry.isFile()&&allowedShipping(rel)){const info=await stat(full);invariant(info.size<=MAX_FILE,'ERR_BACKUP_SIZE',`Backup file too large: ${rel}`);out.push({rel,full,size:info.size});}}return out;}
export async function createBackup({projectId,projectRoot,serverSecret,outputPath,extraEvidenceFiles=[]}){const shippingRoot=path.join(path.resolve(projectRoot),'.shipping');const candidates=await walk(shippingRoot);const files=[];let total=0;for(const item of candidates){const bytes=await readFile(item.full);total+=bytes.length;invariant(total<=MAX_TOTAL,'ERR_BACKUP_SIZE','Backup exceeds total size limit');files.push({path:`shipping/${item.rel}`,bytes:bytes.toString('base64'),size:bytes.length,sha256:sha256(bytes)});}for(const item of extraEvidenceFiles){if(!item?.source||!item?.logicalPath)continue;const logical=safeRelative(item.logicalPath);const bytes=await readFile(item.source);total+=bytes.length;invariant(bytes.length<=MAX_FILE&&total<=MAX_TOTAL,'ERR_BACKUP_SIZE','Backup evidence exceeds size limit');files.push({path:`evidence/${logical}`,bytes:bytes.toString('base64'),size:bytes.length,sha256:sha256(bytes),restore:false});}files.sort((a,b)=>a.path.localeCompare(b.path));const body={schema:'shipping-harness/backup-v1',backupId:randomId('BACKUP'),projectId,createdAt:new Date().toISOString(),files,totalBytes:total};const bundle={...body,signature:hmac(body,serverSecret)};await mkdir(path.dirname(outputPath),{recursive:true});await writeFile(outputPath,`${JSON.stringify(bundle,null,2)}\n`,{mode:0o600});return{backupId:bundle.backupId,path:outputPath,fileCount:files.length,totalBytes:total,signature:bundle.signature};}
export function validateBackup(bundle,{projectId,serverSecret}){invariant(bundle?.schema==='shipping-harness/backup-v1'&&bundle.projectId===projectId,'ERR_BACKUP_SCHEMA','Backup project or schema mismatch');const unsigned={...bundle};delete unsigned.signature;invariant(safeHex(hmac(unsigned,serverSecret),bundle.signature),'ERR_BACKUP_SIGNATURE','Backup signature is invalid');let total=0;for(const file of bundle.files??[]){safeRelative(file.path);const bytes=Buffer.from(file.bytes,'base64');invariant(bytes.length===file.size&&sha256(bytes)===file.sha256,'ERR_BACKUP_INTEGRITY',`Backup file integrity failed: ${file.path}`);total+=bytes.length;}invariant(total===bundle.totalBytes&&total<=MAX_TOTAL,'ERR_BACKUP_SIZE','Backup total size mismatch');return bundle;}
export async function restoreBackup({projectId,projectRoot,serverSecret,bundlePath}){const bundle=validateBackup(JSON.parse(await readFile(bundlePath,'utf8')),{projectId,serverSecret});const shippingRoot=path.join(path.resolve(projectRoot),'.shipping');let currentState=null;try{currentState=JSON.parse(await readFile(path.join(shippingRoot,'state.json'),'utf8')).state;}catch{}invariant(!['RUNNING','VERIFYING','FIXING'].includes(currentState),'ERR_BACKUP_ACTIVE','Pause or stop active work before restore');const stage=path.join(path.dirname(shippingRoot),`.shipping-restore-${bundle.backupId}`);await rm(stage,{recursive:true,force:true});await mkdir(stage,{recursive:true});for(const file of bundle.files){if(!file.path.startsWith('shipping/'))continue;const relative=safeRelative(file.path.slice('shipping/'.length));invariant(allowedShipping(relative),'ERR_BACKUP_PATH',`Restore path is not an allowed Shipping state path: ${relative}`);const target=path.join(stage,relative);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,Buffer.from(file.bytes,'base64'),{mode:0o600});}const previous=path.join(path.dirname(shippingRoot),`.shipping-before-restore-${Date.now()}`);try{await rename(shippingRoot,previous);}catch(e){if(e.code!=='ENOENT')throw e;}try{await rename(stage,shippingRoot);}catch(e){try{await rename(previous,shippingRoot);}catch{}throw e;}return{restored:true,backupId:bundle.backupId,previousPath:previous,fileCount:bundle.files.filter(f=>f.path.startsWith('shipping/')).length};}
export function migrateBackup(bundle){invariant(bundle?.schema==='shipping-harness/backup-v1','ERR_BACKUP_MIGRATION','Unsupported backup schema');return bundle;}
