import path from 'node:path';
import { issueApprovalReceipt, validateApprovalReceipt } from './approval.mjs';
import { createBackup, restoreBackup } from './backup.mjs';
import { validateRemoteRequest } from './request.mjs';
import { invariant } from './policy.mjs';
export class RateLimiter{constructor(limit=30,windowMs=60000){this.limit=limit;this.windowMs=windowMs;this.entries=new Map();}claim(actor,now=Date.now()){const item=this.entries.get(actor);if(!item||now-item.start>=this.windowMs){this.entries.set(actor,{start:now,count:1});return;}invariant(item.count<this.limit,'ERR_REMOTE_RATE','Remote rate limit exceeded');item.count+=1;}}
function boundedParams(params,keys){for(const key of Object.keys(params??{}))invariant(keys.includes(key),'ERR_REMOTE_ARGUMENT',`Unknown action parameter: ${key}`);return params??{};}
function extractRelease(status){return status?.contract?.release??status?.state?.release??status?.release??null;}
export class InternalRemoteGateway{constructor({config,replayStore,adapter,notifications,backupRoot,rateLimiter}){this.config=config;this.replayStore=replayStore;this.adapter=adapter;this.notifications=notifications;this.backupRoot=path.resolve(backupRoot);this.rateLimiter=rateLimiter??new RateLimiter(config.ratePerMinute);}
 async handle(raw,{now=Date.now()}={}){const verified=validateRemoteRequest(raw,this.config,{now});this.rateLimiter.claim(verified.actor.id,now);await this.replayStore.claim(verified.actor.id,raw.nonce,now);const p=raw.params??{};let result;
  if(raw.action==='approval/issue'){boundedParams(p,['proposalId','proposalHash','release','confirm']);invariant(p.confirm===true,'ERR_REMOTE_APPROVAL','Explicit approval confirmation is required');result=issueApprovalReceipt({projectId:raw.projectId,release:p.release,proposalId:p.proposalId,proposalHash:p.proposalHash,actorId:raw.actorId,serverSecret:this.config.serverSecret,now});}
  else if(raw.action==='shipping/approve'){boundedParams(p,['proposalId','proposalHash','release']);validateApprovalReceipt(raw.approvalReceipt,{projectId:raw.projectId,release:p.release,proposalId:p.proposalId,proposalHash:p.proposalHash,actorId:raw.actorId,serverSecret:this.config.serverSecret,now});result=await this.adapter.call(raw.projectId,raw.action,p);}
  else if(raw.action==='notifications/list'){boundedParams(p,['afterId','limit']);result=await this.notifications.list({projectId:raw.projectId,afterId:p.afterId,limit:p.limit});}
  else if(raw.action==='backup/create'){boundedParams(p,[]);const project=this.config.projects[raw.projectId];const output=path.join(this.backupRoot,raw.projectId,`backup-${Date.now()}.json`);const extras=project.omoRuntimeManifest?[{source:project.omoRuntimeManifest,logicalPath:'omo/runtime-manifest.json'}]:[];result=await createBackup({projectId:raw.projectId,projectRoot:project.root,serverSecret:this.config.serverSecret,outputPath:output,extraEvidenceFiles:extras});}
  else if(raw.action==='backup/restore'){boundedParams(p,['bundlePath']);const project=this.config.projects[raw.projectId];invariant(typeof p.bundlePath==='string'&&path.resolve(p.bundlePath).startsWith(path.join(this.backupRoot,raw.projectId)),'ERR_BACKUP_PATH','Restore bundle is outside the project backup root');result=await restoreBackup({projectId:raw.projectId,projectRoot:project.root,serverSecret:this.config.serverSecret,bundlePath:p.bundlePath});}
  else if(raw.action==='health/read'){boundedParams(p,[]);result={status:'healthy',internalOnly:true,tlsRequired:true,publicListener:false,arbitraryShell:false};}
  else{const allowed={ 'shipping/status':[], 'shipping/start':['goal','release','projectName','mode'], 'shipping/pause':['reason'], 'shipping/resume':['reason'], 'shipping/abort':['reason'], 'shipping/verify':[], 'shipping/close':[], 'evidence/summary':[] };boundedParams(p,allowed[raw.action]??[]);result=await this.adapter.call(raw.projectId,raw.action,p);}
  const state=result?.state?.state??result?.state??null;const issueCount=result?.issues?.counts?.BLOCKER??result?.blockers??null;if(state==='BLOCKED'||issueCount>0)await this.notifications.append({projectId:raw.projectId,type:'BLOCKED',actorId:raw.actorId,state,blockers:issueCount});if(state==='CLOSED')await this.notifications.append({projectId:raw.projectId,type:'CLOSED',actorId:raw.actorId,state,release:extractRelease(result)});return{schema:'shipping-harness/remote-response-v1',requestId:raw.requestId,ok:true,result};}
}
export function remoteError(requestId,error){return{schema:'shipping-harness/remote-response-v1',requestId:typeof requestId==='string'?requestId:'unknown',ok:false,error:{code:error.code??'ERR_REMOTE_INTERNAL',message:String(error.message??'Internal remote error').replace(/(secret|token|authorization)\s*[:=]\s*\S+/giu,'$1=[REDACTED]')}};}
