import net from 'node:net';
export function invariant(condition,code,message,details){if(!condition){const e=new Error(message);e.code=code;e.details=details;throw e;}}
export const ACTION_PERMISSION=Object.freeze({'shipping/status':'read','shipping/start':'write','shipping/approve':'approve','shipping/pause':'control','shipping/resume':'control','shipping/abort':'control','shipping/verify':'write','shipping/close':'close','evidence/summary':'read','approval/issue':'approve','notifications/list':'read','backup/create':'admin','backup/restore':'admin','health/read':'read'});
export const ALLOWED_ACTIONS=Object.freeze(Object.keys(ACTION_PERMISSION));
const FORBIDDEN_KEYS=new Set(['command','shell','argv','args','env','environment','cwd','executable','script','rawCommand']);
export function rejectArbitraryExecution(value,depth=0){invariant(depth<=16,'ERR_REMOTE_DEPTH','Remote input nesting is too deep');if(Array.isArray(value)){invariant(value.length<=256,'ERR_REMOTE_SIZE','Remote array is too large');for(const item of value)rejectArbitraryExecution(item,depth+1);return;}if(value&&typeof value==='object'){invariant(Object.keys(value).length<=128,'ERR_REMOTE_SIZE','Remote object is too large');for(const [key,nested] of Object.entries(value)){invariant(!FORBIDDEN_KEYS.has(key),'ERR_REMOTE_ARBITRARY',`Remote execution field is forbidden: ${key}`);rejectArbitraryExecution(nested,depth+1);}}}
export function privateListenHost(host){if(host==='localhost'||host==='::1')return true;if(net.isIP(host)!==4)return false;const p=host.split('.').map(Number);return p[0]===127||p[0]===10||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168);}
export function validateListen(host){invariant(privateListenHost(host),'ERR_REMOTE_LISTEN','Gateway listen host must be loopback or private IPv4; public/unspecified listeners are forbidden');return host;}
export function boundedString(value,label,max=4096){invariant(typeof value==='string'&&value.length>0&&Buffer.byteLength(value,'utf8')<=max,'ERR_REMOTE_ARGUMENT',`${label} is required and bounded`);return value;}
